/* Auto-generated by fetch_data.py · do not edit manually */
window.NEWS_DATA = {
  "updated": "2026-05-25",
  "source": "Curated source directory + live RSS where exposed",
  "sources": [
    {
      "name": "CNBC Indonesia",
      "tag": "Market & Investing",
      "url": "https://www.cnbcindonesia.com/market",
      "color": "#003D7A",
      "letter": "CN"
    },
    {
      "name": "Bisnis Indonesia",
      "tag": "Bisnis & Pasar Modal",
      "url": "https://www.bisnis.com/topic/82/pasar-modal",
      "color": "#0066B3",
      "letter": "BI"
    },
    {
      "name": "Kontan",
      "tag": "Investasi & Keuangan",
      "url": "https://investasi.kontan.co.id/",
      "color": "#E31E24",
      "letter": "KO"
    },
    {
      "name": "Kompas Money",
      "tag": "Ekonomi & Finansial",
      "url": "https://money.kompas.com/",
      "color": "#005CAA",
      "letter": "KM"
    },
    {
      "name": "Katadata",
      "tag": "Data-driven Ekonomi",
      "url": "https://katadata.co.id/finansial",
      "color": "#F26522",
      "letter": "KD"
    },
    {
      "name": "CNN Indonesia",
      "tag": "Ekonomi & Bisnis",
      "url": "https://www.cnnindonesia.com/ekonomi",
      "color": "#CC0000",
      "letter": "CN"
    },
    {
      "name": "Investor Daily",
      "tag": "Pasar Modal",
      "url": "https://investor.id/market",
      "color": "#1A5E8C",
      "letter": "ID"
    },
    {
      "name": "IDX Channel",
      "tag": "Bursa Indonesia",
      "url": "https://www.idxchannel.com/",
      "color": "#00417A",
      "letter": "IX"
    },
    {
      "name": "MSCI",
      "tag": "Index Methodology",
      "url": "https://www.msci.com/research-and-insights",
      "color": "#003366",
      "letter": "MS"
    }
  ],
  "articles": [
    {
      "source": "Kontan",
      "title": "IHSG Berpeluang Menguat Selasa (26/5), Saham Bank Jadi Motor Saat Asing Net Sell",
      "url": "https://investasi.kontan.co.id/news/ihsg-berpeluang-menguat-selasa-265-saham-bank-jadi-motor-saat-asing-net-sell",
      "published": "Mon, 25 May 2026 21:35:03 +0700"
    },
    {
      "source": "Kontan",
      "title": "BI Rate Naik, Investor Obligasi Kini Ubah Strategi Fokus Kupon & Tenor Pendek",
      "url": "https://investasi.kontan.co.id/news/bi-rate-naik-investor-obligasi-kini-ubah-strategi-fokus-kupon-tenor-pendek",
      "published": "Mon, 25 May 2026 20:37:12 +0700"
    },
    {
      "source": "Kontan",
      "title": "Kinerja Sumber Global (SGER) Ditopang Harga Batubara hingga Diversifikasi Bisnis",
      "url": "https://investasi.kontan.co.id/news/kinerja-sumber-global-sger-ditopang-harga-batubara-hingga-diversifikasi-bisnis",
      "published": "Mon, 25 May 2026 20:15:49 +0700"
    },
    {
      "source": "Kontan",
      "title": "Harga Aluminium Melesat, Emiten Ini Berpotensi Diuntungkan",
      "url": "https://investasi.kontan.co.id/news/harga-aluminium-melesat-emiten-ini-berpotensi-diuntungkan",
      "published": "Mon, 25 May 2026 19:42:06 +0700"
    },
    {
      "source": "Kontan",
      "title": "Aksi Net Sell dari Pasar Saham Capai Rp 44 T, Ini Saham Incaran Investor Asing",
      "url": "https://investasi.kontan.co.id/news/aksi-net-sell-dari-pasar-saham-capai-rp-44-t-ini-saham-incaran-investor-asing",
      "published": "Mon, 25 May 2026 19:33:35 +0700"
    }
  ]
};
