/* Auto-generated by fetch_data.py v2 · do not edit manually
   This snapshot uses the curated NEWS_FALLBACK because the previous workflow
   run produced 0 articles (all RSS feeds returned empty / blocked the bot).
   The next scheduled run will replace this with live RSS data automatically. */
window.NEWS_DATA = {
  "updated": "2026-05-27",
  "source": "Curated fallback (live RSS unavailable)",
  "articles_sample": true,
  "sources": [
    { "name":"Kompas Ekonomi",   "tag":"Ekonomi Nasional",            "url":"https://money.kompas.com/",                       "color":"#005CAA", "letter":"KM" },
    { "name":"Detik Finance",    "tag":"Finansial & Pasar Modal",     "url":"https://finance.detik.com/",                       "color":"#003366", "letter":"DF" },
    { "name":"CNN Indonesia",    "tag":"Ekonomi & Bisnis",            "url":"https://www.cnnindonesia.com/ekonomi",             "color":"#CC0000", "letter":"CN" },
    { "name":"CNBC Indonesia",   "tag":"Market & Investing",          "url":"https://www.cnbcindonesia.com/market",             "color":"#003D7A", "letter":"CB" },
    { "name":"Tempo Bisnis",     "tag":"Bisnis & Ekonomi",            "url":"https://bisnis.tempo.co/",                         "color":"#D32F2F", "letter":"TM" },
    { "name":"Kontan",           "tag":"Investasi & Keuangan",        "url":"https://investasi.kontan.co.id/",                  "color":"#E31E24", "letter":"KO" },
    { "name":"Bisnis Indonesia", "tag":"Bisnis & Pasar Modal",        "url":"https://www.bisnis.com/topic/82/pasar-modal",      "color":"#0066B3", "letter":"BI" },
    { "name":"Katadata",         "tag":"Data-driven Ekonomi",         "url":"https://katadata.co.id/finansial",                 "color":"#F26522", "letter":"KD" },
    { "name":"Investor Daily",   "tag":"Pasar Modal",                 "url":"https://investor.id/market",                       "color":"#1A5E8C", "letter":"ID" },
    { "name":"IDX Channel",      "tag":"Bursa Indonesia",             "url":"https://www.idxchannel.com/",                      "color":"#00417A", "letter":"IX" },
    { "name":"MSCI",             "tag":"Index Methodology",           "url":"https://www.msci.com/research-and-insights",       "color":"#003366", "letter":"MS" }
  ],
  "articles": [
    { "source":"CNBC Indonesia",  "category":"Macro",      "title":"MSCI Pertimbangkan Turunkan Status Indonesia ke Frontier Market — USD 80 Miliar Kapitalisasi Pasar Hilang", "url":"https://www.cnbcindonesia.com/market",        "published":"2026-01-28" },
    { "source":"Bisnis Indonesia","category":"Regulator",  "title":"OJK Turunkan Ambang Wajib Lapor Kepemilikan Saham dari 5% ke 1% Pasca Krisis MSCI",                        "url":"https://www.bisnis.com/topic/82/pasar-modal", "published":"2026-02-15" },
    { "source":"Kontan",          "category":"ESG",        "title":"IDX Carbon Catat Volume Perdagangan Karbon Tembus Rp 50 Miliar di Kuartal Pertama 2026",                   "url":"https://investasi.kontan.co.id/",             "published":"2026-03-10" },
    { "source":"Kompas Ekonomi",  "category":"ESG",        "title":"Sukuk Hijau Ritel SR020 Resmi Terbit, Sasaran Pendanaan Proyek Energi Terbarukan dan Air Bersih",           "url":"https://money.kompas.com/",                   "published":"2026-04-22" },
    { "source":"CNN Indonesia",   "category":"Macro",      "title":"IHSG Mulai Pulih Pasca Krisis MSCI Januari 2026, Investor Asing Mulai Masuk Lagi",                         "url":"https://www.cnnindonesia.com/ekonomi",        "published":"2026-05-05" },
    { "source":"Katadata",        "category":"Regulator",  "title":"TKBI v2 Resmi Berlaku, Tambah Sektor Konstruksi, Real Estate, dan Transportasi",                            "url":"https://katadata.co.id/finansial",            "published":"2025-02-12" },
    { "source":"Investor Daily", "category":"ESG",        "title":"JETP Salurkan USD 21,6 Miliar untuk Pensiun Dini PLTU di Indonesia — Roadmap Transisi Energi 2030",         "url":"https://investor.id/market",                  "published":"2025-11-08" },
    { "source":"IDX Channel",     "category":"Market",     "title":"IDX ESG Leaders Review Semesteran: 3 Saham Baru Masuk Indeks, 2 Saham Dikeluarkan",                         "url":"https://www.idxchannel.com/",                 "published":"2026-06-15" },
    { "source":"Detik Finance",   "category":"Market",     "title":"Bursa Efek Indonesia Catat Pertumbuhan Investor Ritel Tembus 21 Juta SID di Awal 2026",                     "url":"https://finance.detik.com/",                  "published":"2026-04-30" },
    { "source":"Tempo Bisnis",    "category":"ESG",        "title":"Bank Mandiri Salurkan Pembiayaan Hijau Rp 285 Triliun, Tertinggi di Indonesia",                              "url":"https://bisnis.tempo.co/",                    "published":"2026-03-25" },
    { "source":"MSCI",            "category":"Methodology","title":"MSCI Indonesia Index Review — Frontier Market Reclassification Watch List Update",                          "url":"https://www.msci.com/research-and-insights",  "published":"2026-05-01" },
    { "source":"Kontan",          "category":"ESG",        "title":"Sustainalytics Naikkan Skor ESG 5 Emiten Big Cap Indonesia Pasca Reformasi POJK 13/2025",                    "url":"https://investasi.kontan.co.id/",             "published":"2026-04-10" }
  ]
};
