/* Auto-generated by fetch_data.py v2 · do not edit manually */
window.NEWS_DATA = {
  "updated": "2026-05-29",
  "source": "Live RSS via fetch_data.py v2",
  "articles_sample": false,
  "sources": [
    {
      "name": "Kompas Ekonomi",
      "tag": "Ekonomi Nasional",
      "url": "https://money.kompas.com/",
      "color": "#005CAA",
      "letter": "KM"
    },
    {
      "name": "Detik Finance",
      "tag": "Finansial &amp; Pasar Modal",
      "url": "https://finance.detik.com/",
      "color": "#003366",
      "letter": "DF"
    },
    {
      "name": "CNN Indonesia",
      "tag": "Ekonomi &amp; Bisnis",
      "url": "https://www.cnnindonesia.com/ekonomi",
      "color": "#CC0000",
      "letter": "CN"
    },
    {
      "name": "CNBC Indonesia",
      "tag": "Market &amp; Investing",
      "url": "https://www.cnbcindonesia.com/market",
      "color": "#003D7A",
      "letter": "CB"
    },
    {
      "name": "Tempo Bisnis",
      "tag": "Bisnis &amp; Ekonomi",
      "url": "https://bisnis.tempo.co/",
      "color": "#D32F2F",
      "letter": "TM"
    },
    {
      "name": "Kontan",
      "tag": "Investasi &amp; Keuangan",
      "url": "https://investasi.kontan.co.id/",
      "color": "#E31E24",
      "letter": "KO"
    },
    {
      "name": "Bisnis Indonesia",
      "tag": "Bisnis &amp; Pasar Modal",
      "url": "https://www.bisnis.com/topic/82/pasar-modal",
      "color": "#0066B3",
      "letter": "BI"
    },
    {
      "name": "Katadata",
      "tag": "Data-driven Ekonomi",
      "url": "https://katadata.co.id/finansial",
      "color": "#F26522",
      "letter": "KD"
    },
    {
      "name": "Investor Daily",
      "tag": "Pasar Modal",
      "url": "https://investor.id/market",
      "color": "#1A5E8C",
      "letter": "ID"
    },
    {
      "name": "IDX Channel",
      "tag": "Bursa Indonesia",
      "url": "https://www.idxchannel.com/",
      "color": "#00417A",
      "letter": "IX"
    },
    {
      "name": "MSCI",
      "tag": "Index Methodology",
      "url": "https://www.msci.com/research-and-insights",
      "color": "#003366",
      "letter": "MS"
    }
  ],
  "articles": [
    {
      "source": "Tempo Bisnis",
      "category": "Bisnis & Ekonomi",
      "title": "Wamentan: DSI Tak Ambil Untung untuk Ekspor Minyak Sawit",
      "url": "https://bisnis.tempo.co/read/2105927/wamentan-dsi-tak-ambil-untung-untuk-ekspor-minyak-sawit",
      "published": "Fri, 29 May 2026 21:24:53 +0700"
    },
    {
      "source": "Tempo Bisnis",
      "category": "Bisnis & Ekonomi",
      "title": "IHSG Ditutup Melemah, Pasar Modal Masih Hadapi Volatilitas",
      "url": "https://bisnis.tempo.co/read/2105917/ihsg-ditutup-melemah-pasar-modal-masih-hadapi-volatilitas",
      "published": "Fri, 29 May 2026 20:21:35 +0700"
    },
    {
      "source": "Tempo Bisnis",
      "category": "Bisnis & Ekonomi",
      "title": "Lemigas Berpeluang Bisa Impor Minyak Rusia",
      "url": "https://bisnis.tempo.co/read/2105903/lemigas-berpeluang-bisa-impor-minyak-rusia",
      "published": "Fri, 29 May 2026 20:08:00 +0700"
    },
    {
      "source": "Tempo Bisnis",
      "category": "Bisnis & Ekonomi",
      "title": "Pelaporan SPT Tahunan Capai 13,45 Juta",
      "url": "https://bisnis.tempo.co/read/2105900/pelaporan-spt-tahunan-capai-1345-juta",
      "published": "Fri, 29 May 2026 19:02:00 +0700"
    },
    {
      "source": "Tempo Bisnis",
      "category": "Bisnis & Ekonomi",
      "title": "Rupiah Makin Terpuruk, BI: Dipengaruhi Ketidakpastian Global",
      "url": "https://bisnis.tempo.co/read/2105895/rupiah-makin-terpuruk-bi-dipengaruhi-ketidakpastian-global",
      "published": "Fri, 29 May 2026 18:03:00 +0700"
    }
  ]
};
