/* Auto-generated by fetch_data.py v2 · do not edit manually */
window.STOCKS_DATA = {
  "updated": "2026-10-07",
  "source": "Live yfinance + curated IDX/KEHATI flags + curated ESG pillars (Sustainalytics paywall'd)",
  "is_sample": false,
  "methodology": {
    "data_sources": {
      "price_financials": "yfinance (free)",
      "index_membership": "IDX ESG Methodology + KEHATI SRI announcements (curated)",
      "esg_pillars": "Illustrative scores (real Sustainalytics/MSCI need paid API)"
    },
    "hybrid_esg_score": {
      "formula": "0.5*pillar_avg + 0.3*financial_health + 0.2*membership_score",
      "range": "0-10",
      "components": {
        "pillar_avg": "(E + S + G) / 3 from curated ESG pillars",
        "financial_health": "P/E inverse + dividend yield + market cap (normalized)",
        "membership_score": "10=KEHATI+ESG Leaders, 9=ESG Leaders, 7.5=KEHATI, 5=Syariah, 0=none"
      }
    }
  },
  "benchmark": {
    "jkse": {
      "value": 6192.93,
      "change_1d": 1.21,
      "change_ytd": -29.2,
      "change_1y": -24.2,
      "name": "JCI / IHSG",
      "description": "Jakarta Composite Index"
    },
    "jklq45": {
      "value": 608.16,
      "change_1d": 0.82,
      "change_ytd": -28.6,
      "change_1y": -22.6,
      "name": "LQ45",
      "description": "45 most liquid IDX stocks"
    },
    "jci_value": 6192.93,
    "jci_ytd": -29.2,
    "jci_1y": -24.2,
    "jci_1d": 1.21,
    "note": "Multi-index via yfinance; IHSG cross-checked vs live news"
  },
  "stocks": [
    {
      "ticker": "BBCA",
      "name": "Bank Central Asia",
      "sector": "Banking",
      "price": 6050,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 6.25,
      "pe_ratio": 12.8,
      "market_cap_t": 743.2,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 7.2,
        "g": 8.5
      },
      "hybrid_esg_score": 7.88,
      "hybrid_breakdown": {
        "pillar_avg": 7.5,
        "financial_health": 7.1,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BMRI",
      "name": "Bank Mandiri",
      "sector": "Banking",
      "price": 4100,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 13.24,
      "pe_ratio": 6.1,
      "market_cap_t": 381.2,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.9
      },
      "hybrid_esg_score": 8.34,
      "hybrid_breakdown": {
        "pillar_avg": 7.07,
        "financial_health": 9.36,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BBRI",
      "name": "Bank Rakyat Indonesia",
      "sector": "Banking",
      "price": 3140,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 13.44,
      "pe_ratio": 7.7,
      "market_cap_t": 473.1,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 7.5,
        "g": 7.7
      },
      "hybrid_esg_score": 8.33,
      "hybrid_breakdown": {
        "pillar_avg": 7.13,
        "financial_health": 9.22,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BBNI",
      "name": "Bank Negara Indonesia",
      "sector": "Banking",
      "price": 3440,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 10.1,
      "pe_ratio": 6.2,
      "market_cap_t": 128.2,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.0,
        "s": 6.5,
        "g": 7.2
      },
      "hybrid_esg_score": 7.32,
      "hybrid_breakdown": {
        "pillar_avg": 6.57,
        "financial_health": 8.45,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BRIS",
      "name": "Bank Syariah Indonesia",
      "sector": "Banking (Syariah)",
      "price": 1375,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 2.33,
      "pe_ratio": 7.9,
      "market_cap_t": 63.4,
      "kehati": false,
      "esg_leaders": false,
      "syariah": true,
      "esg": {
        "e": 6.4,
        "s": 7.8,
        "g": 7.5
      },
      "hybrid_esg_score": 6.36,
      "hybrid_breakdown": {
        "pillar_avg": 7.23,
        "financial_health": 5.81,
        "membership_score": 5.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "TLKM",
      "name": "Telkom Indonesia",
      "sector": "Telecom",
      "price": 2310,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 9.79,
      "pe_ratio": 13.4,
      "market_cap_t": 227.7,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 7.5,
        "s": 7.6,
        "g": 8.0
      },
      "hybrid_esg_score": 8.13,
      "hybrid_breakdown": {
        "pillar_avg": 7.7,
        "financial_health": 7.6,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ISAT",
      "name": "Indosat Ooredoo H.",
      "sector": "Telecom",
      "price": 2220,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 5.0,
      "pe_ratio": 9.6,
      "market_cap_t": 71.6,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 6.9,
        "g": 7.0
      },
      "hybrid_esg_score": 5.36,
      "hybrid_breakdown": {
        "pillar_avg": 6.9,
        "financial_health": 6.38,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "EXCL",
      "name": "XL Axiata",
      "sector": "Telecom",
      "price": 2340,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 6.65,
      "pe_ratio": null,
      "market_cap_t": 42.6,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.7,
        "g": 6.8
      },
      "hybrid_esg_score": 5.1,
      "hybrid_breakdown": {
        "pillar_avg": 6.67,
        "financial_health": 5.9,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "UNVR",
      "name": "Unilever Indonesia",
      "sector": "Consumer Staples",
      "price": 1590,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 14.29,
      "pe_ratio": 17.5,
      "market_cap_t": 60.4,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 8.2,
        "s": 7.8,
        "g": 8.4
      },
      "hybrid_esg_score": 8.23,
      "hybrid_breakdown": {
        "pillar_avg": 8.13,
        "financial_health": 7.21,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ICBP",
      "name": "Indofood CBP",
      "sector": "Consumer Staples",
      "price": 6775,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 3.9,
      "pe_ratio": 10.7,
      "market_cap_t": 79.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.9,
        "s": 7.2,
        "g": 7.4
      },
      "hybrid_esg_score": 6.87,
      "hybrid_breakdown": {
        "pillar_avg": 7.17,
        "financial_health": 5.96,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INDF",
      "name": "Indofood Sukses Makmur",
      "sector": "Consumer Staples",
      "price": 6950,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 4.23,
      "pe_ratio": 6.4,
      "market_cap_t": 61.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.1
      },
      "hybrid_esg_score": 6.86,
      "hybrid_breakdown": {
        "pillar_avg": 6.8,
        "financial_health": 6.54,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "AMRT",
      "name": "Sumber Alfaria Trijaya",
      "sector": "Consumer Retail",
      "price": 1225,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 3.31,
      "pe_ratio": 14.3,
      "market_cap_t": 50.3,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 6.8,
        "g": 7.0
      },
      "hybrid_esg_score": 4.88,
      "hybrid_breakdown": {
        "pillar_avg": 6.67,
        "financial_health": 5.16,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ASII",
      "name": "Astra International",
      "sector": "Industrial / Auto",
      "price": 4780,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 8.09,
      "pe_ratio": 6.5,
      "market_cap_t": 190.8,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 7.4,
        "g": 8.1
      },
      "hybrid_esg_score": 8.11,
      "hybrid_breakdown": {
        "pillar_avg": 7.43,
        "financial_health": 7.99,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "KLBF",
      "name": "Kalbe Farma",
      "sector": "Healthcare",
      "price": 755,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 2.65,
      "pe_ratio": 9.5,
      "market_cap_t": 34.2,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 7.1,
        "s": 7.5,
        "g": 7.8
      },
      "hybrid_esg_score": 7.38,
      "hybrid_breakdown": {
        "pillar_avg": 7.47,
        "financial_health": 5.48,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "KAEF",
      "name": "Kimia Farma",
      "sector": "Healthcare",
      "price": 446,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": null,
      "pe_ratio": null,
      "market_cap_t": 2.5,
      "kehati": false,
      "esg_leaders": false,
      "syariah": true,
      "esg": {
        "e": 6.4,
        "s": 6.9,
        "g": 5.8
      },
      "hybrid_esg_score": 5.18,
      "hybrid_breakdown": {
        "pillar_avg": 6.37,
        "financial_health": 3.33,
        "membership_score": 5.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ADRO",
      "name": "Adaro Energy",
      "sector": "Energy (Coal)",
      "price": 2600,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 9.1,
      "pe_ratio": 7.7,
      "market_cap_t": 74.9,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 3.8,
        "s": 5.5,
        "g": 6.8
      },
      "hybrid_esg_score": 5.02,
      "hybrid_breakdown": {
        "pillar_avg": 5.37,
        "financial_health": 7.79,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "PTBA",
      "name": "Bukit Asam",
      "sector": "Energy (Coal)",
      "price": 3380,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 3.37,
      "pe_ratio": 8.2,
      "market_cap_t": 38.9,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 3.5,
        "s": 5.8,
        "g": 6.5
      },
      "hybrid_esg_score": 4.4,
      "hybrid_breakdown": {
        "pillar_avg": 5.27,
        "financial_health": 5.9,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ANTM",
      "name": "Aneka Tambang",
      "sector": "Mining (Nickel/Gold)",
      "price": 3230,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 6.46,
      "pe_ratio": 8.7,
      "market_cap_t": 77.6,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.8,
        "s": 6.4,
        "g": 6.9
      },
      "hybrid_esg_score": 6.76,
      "hybrid_breakdown": {
        "pillar_avg": 6.37,
        "financial_health": 6.92,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INCO",
      "name": "Vale Indonesia",
      "sector": "Mining (Nickel)",
      "price": 4260,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 1.8,
      "pe_ratio": 17.2,
      "market_cap_t": 44.9,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 6.5,
        "g": 6.8
      },
      "hybrid_esg_score": 4.54,
      "hybrid_breakdown": {
        "pillar_avg": 6.5,
        "financial_health": 4.31,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "MEDC",
      "name": "Medco Energi",
      "sector": "Energy (Oil & Gas)",
      "price": 1460,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 4.48,
      "pe_ratio": 6.3,
      "market_cap_t": 36.1,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.2,
        "s": 6.0,
        "g": 6.4
      },
      "hybrid_esg_score": 4.86,
      "hybrid_breakdown": {
        "pillar_avg": 5.87,
        "financial_health": 6.43,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "PGAS",
      "name": "Perusahaan Gas Negara",
      "sector": "Utilities (Gas)",
      "price": 1420,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 8.85,
      "pe_ratio": 8.9,
      "market_cap_t": 34.4,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.5,
        "s": 6.7,
        "g": 7.2
      },
      "hybrid_esg_score": 6.92,
      "hybrid_breakdown": {
        "pillar_avg": 6.47,
        "financial_health": 7.28,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "JSMR",
      "name": "Jasa Marga",
      "sector": "Infrastructure (Toll)",
      "price": 2620,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 5.92,
      "pe_ratio": 5.1,
      "market_cap_t": 19.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.0
      },
      "hybrid_esg_score": 6.91,
      "hybrid_breakdown": {
        "pillar_avg": 6.77,
        "financial_health": 6.77,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "SMGR",
      "name": "Semen Indonesia",
      "sector": "Materials (Cement)",
      "price": 1545,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 1.84,
      "pe_ratio": 27.6,
      "market_cap_t": 10.4,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.8,
        "s": 6.5,
        "g": 6.9
      },
      "hybrid_esg_score": 5.43,
      "hybrid_breakdown": {
        "pillar_avg": 6.4,
        "financial_health": 2.43,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INTP",
      "name": "Indocement Tunggal P.",
      "sector": "Materials (Cement)",
      "price": 4960,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 9.22,
      "pe_ratio": 7.0,
      "market_cap_t": 17.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.0,
        "s": 6.7,
        "g": 7.2
      },
      "hybrid_esg_score": 7.03,
      "hybrid_breakdown": {
        "pillar_avg": 6.63,
        "financial_health": 7.39,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BRPT",
      "name": "Barito Pacific",
      "sector": "Petrochemicals/Renew.",
      "price": 1430,
      "change_1d": NaN,
      "change_ytd": NaN,
      "change_1y": NaN,
      "dividend_yield": 11.0,
      "pe_ratio": 56.6,
      "market_cap_t": 134.0,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.4,
        "s": 5.8,
        "g": 5.9
      },
      "hybrid_esg_score": 4.51,
      "hybrid_breakdown": {
        "pillar_avg": 5.7,
        "financial_health": 5.54,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    }
  ]
};
