/* Auto-generated by fetch_data.py v2 · do not edit manually */
window.STOCKS_DATA = {
  "updated": "2026-08-03",
  "source": "Live yfinance + curated IDX/KEHATI flags + curated ESG pillars (Sustainalytics paywall'd)",
  "is_sample": false,
  "methodology": {
    "data_sources": {
      "price_financials": "yfinance (free)",
      "index_membership": "IDX ESG Methodology + KEHATI SRI announcements (curated)",
      "esg_pillars": "Illustrative scores (real Sustainalytics/MSCI need paid API)"
    },
    "hybrid_esg_score": {
      "formula": "0.5*pillar_avg + 0.3*financial_health + 0.2*membership_score",
      "range": "0-10",
      "components": {
        "pillar_avg": "(E + S + G) / 3 from curated ESG pillars",
        "financial_health": "P/E inverse + dividend yield + market cap (normalized)",
        "membership_score": "10=KEHATI+ESG Leaders, 9=ESG Leaders, 7.5=KEHATI, 5=Syariah, 0=none"
      }
    }
  },
  "benchmark": {
    "jkse": {
      "value": 6234.5,
      "change_1d": -0.03,
      "change_ytd": -28.7,
      "change_1y": -16.5,
      "name": "JCI / IHSG",
      "description": "Jakarta Composite Index"
    },
    "jklq45": {
      "value": 623.93,
      "change_1d": 0.43,
      "change_ytd": -26.8,
      "change_1y": -20.8,
      "name": "LQ45",
      "description": "45 most liquid IDX stocks"
    },
    "jci_value": 6234.5,
    "jci_ytd": -28.7,
    "jci_1y": -16.5,
    "jci_1d": -0.03,
    "note": "Multi-index via yfinance; IHSG cross-checked vs live news"
  },
  "stocks": [
    {
      "ticker": "BBCA",
      "name": "Bank Central Asia",
      "sector": "Banking",
      "price": 6300,
      "change_1d": -0.4,
      "change_ytd": -18.1,
      "change_1y": -20.0,
      "dividend_yield": 5.63,
      "pe_ratio": 13.4,
      "market_cap_t": 774.1,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 7.2,
        "g": 8.5
      },
      "hybrid_esg_score": 7.81,
      "hybrid_breakdown": {
        "pillar_avg": 7.5,
        "financial_health": 6.87,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BMRI",
      "name": "Bank Mandiri",
      "sector": "Banking",
      "price": 4170,
      "change_1d": -0.48,
      "change_ytd": -8.7,
      "change_1y": 0.2,
      "dividend_yield": 11.38,
      "pe_ratio": 6.2,
      "market_cap_t": 389.2,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.9
      },
      "hybrid_esg_score": 8.29,
      "hybrid_breakdown": {
        "pillar_avg": 7.07,
        "financial_health": 9.18,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BBRI",
      "name": "Bank Rakyat Indonesia",
      "sector": "Banking",
      "price": 3020,
      "change_1d": -0.66,
      "change_ytd": -11.7,
      "change_1y": -10.1,
      "dividend_yield": 13.75,
      "pe_ratio": 7.8,
      "market_cap_t": 454.7,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 7.5,
        "g": 7.7
      },
      "hybrid_esg_score": 8.33,
      "hybrid_breakdown": {
        "pillar_avg": 7.13,
        "financial_health": 9.2,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BBNI",
      "name": "Bank Negara Indonesia",
      "sector": "Banking",
      "price": 3520,
      "change_1d": -0.28,
      "change_ytd": -10.2,
      "change_1y": -4.6,
      "dividend_yield": 9.9,
      "pe_ratio": 6.5,
      "market_cap_t": 131.1,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.0,
        "s": 6.5,
        "g": 7.2
      },
      "hybrid_esg_score": 7.29,
      "hybrid_breakdown": {
        "pillar_avg": 6.57,
        "financial_health": 8.36,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BRIS",
      "name": "Bank Syariah Indonesia",
      "sector": "Banking (Syariah)",
      "price": 1795,
      "change_1d": -1.37,
      "change_ytd": -15.4,
      "change_1y": -33.5,
      "dividend_yield": 1.8,
      "pe_ratio": 10.5,
      "market_cap_t": 82.8,
      "kehati": false,
      "esg_leaders": false,
      "syariah": true,
      "esg": {
        "e": 6.4,
        "s": 7.8,
        "g": 7.5
      },
      "hybrid_esg_score": 6.24,
      "hybrid_breakdown": {
        "pillar_avg": 7.23,
        "financial_health": 5.42,
        "membership_score": 5.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "TLKM",
      "name": "Telkom Indonesia",
      "sector": "Telecom",
      "price": 2740,
      "change_1d": 4.18,
      "change_ytd": -14.6,
      "change_1y": -2.2,
      "dividend_yield": 8.49,
      "pe_ratio": 15.4,
      "market_cap_t": 270.4,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 7.5,
        "s": 7.6,
        "g": 8.0
      },
      "hybrid_esg_score": 7.96,
      "hybrid_breakdown": {
        "pillar_avg": 7.7,
        "financial_health": 7.03,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ISAT",
      "name": "Indosat Ooredoo H.",
      "sector": "Telecom",
      "price": 1905,
      "change_1d": 0.26,
      "change_ytd": -15.3,
      "change_1y": -10.0,
      "dividend_yield": 5.84,
      "pe_ratio": 8.2,
      "market_cap_t": 61.4,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 6.9,
        "g": 7.0
      },
      "hybrid_esg_score": 5.47,
      "hybrid_breakdown": {
        "pillar_avg": 6.9,
        "financial_health": 6.74,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "EXCL",
      "name": "XL Axiata",
      "sector": "Telecom",
      "price": 2530,
      "change_1d": 3.69,
      "change_ytd": -32.5,
      "change_1y": 2.2,
      "dividend_yield": 6.52,
      "pe_ratio": null,
      "market_cap_t": 46.0,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.7,
        "g": 6.8
      },
      "hybrid_esg_score": 5.1,
      "hybrid_breakdown": {
        "pillar_avg": 6.67,
        "financial_health": 5.88,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "UNVR",
      "name": "Unilever Indonesia",
      "sector": "Consumer Staples",
      "price": 1740,
      "change_1d": -0.85,
      "change_ytd": -28.7,
      "change_1y": 9.8,
      "dividend_yield": 12.99,
      "pe_ratio": 17.8,
      "market_cap_t": 66.1,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 8.2,
        "s": 7.8,
        "g": 8.4
      },
      "hybrid_esg_score": 8.23,
      "hybrid_breakdown": {
        "pillar_avg": 8.13,
        "financial_health": 7.2,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ICBP",
      "name": "Indofood CBP",
      "sector": "Consumer Staples",
      "price": 7200,
      "change_1d": 3.23,
      "change_ytd": -7.3,
      "change_1y": -21.6,
      "dividend_yield": 3.8,
      "pe_ratio": 9.2,
      "market_cap_t": 84.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.9,
        "s": 7.2,
        "g": 7.4
      },
      "hybrid_esg_score": 6.93,
      "hybrid_breakdown": {
        "pillar_avg": 7.17,
        "financial_health": 6.15,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INDF",
      "name": "Indofood Sukses Makmur",
      "sector": "Consumer Staples",
      "price": 7075,
      "change_1d": 1.43,
      "change_ytd": 10.6,
      "change_1y": -11.8,
      "dividend_yield": 4.16,
      "pe_ratio": 5.7,
      "market_cap_t": 62.1,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.1
      },
      "hybrid_esg_score": 6.89,
      "hybrid_breakdown": {
        "pillar_avg": 6.8,
        "financial_health": 6.62,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "AMRT",
      "name": "Sumber Alfaria Trijaya",
      "sector": "Consumer Retail",
      "price": 1325,
      "change_1d": 0.0,
      "change_ytd": -31.2,
      "change_1y": -40.3,
      "dividend_yield": 3.13,
      "pe_ratio": 15.6,
      "market_cap_t": 54.4,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 6.8,
        "g": 7.0
      },
      "hybrid_esg_score": 4.82,
      "hybrid_breakdown": {
        "pillar_avg": 6.67,
        "financial_health": 4.96,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ASII",
      "name": "Astra International",
      "sector": "Industrial / Auto",
      "price": 5050,
      "change_1d": -0.98,
      "change_ytd": -22.0,
      "change_1y": 7.4,
      "dividend_yield": 7.65,
      "pe_ratio": 6.4,
      "market_cap_t": 202.3,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 7.4,
        "g": 8.1
      },
      "hybrid_esg_score": 8.08,
      "hybrid_breakdown": {
        "pillar_avg": 7.43,
        "financial_health": 7.89,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "KLBF",
      "name": "Kalbe Farma",
      "sector": "Healthcare",
      "price": 725,
      "change_1d": 0.0,
      "change_ytd": -38.1,
      "change_1y": -47.3,
      "dividend_yield": 2.76,
      "pe_ratio": 9.1,
      "market_cap_t": 32.8,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 7.1,
        "s": 7.5,
        "g": 7.8
      },
      "hybrid_esg_score": 7.4,
      "hybrid_breakdown": {
        "pillar_avg": 7.47,
        "financial_health": 5.55,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "KAEF",
      "name": "Kimia Farma",
      "sector": "Healthcare",
      "price": 450,
      "change_1d": -0.44,
      "change_ytd": -13.5,
      "change_1y": -18.2,
      "dividend_yield": null,
      "pe_ratio": null,
      "market_cap_t": 2.5,
      "kehati": false,
      "esg_leaders": false,
      "syariah": true,
      "esg": {
        "e": 6.4,
        "s": 6.9,
        "g": 5.8
      },
      "hybrid_esg_score": 5.18,
      "hybrid_breakdown": {
        "pillar_avg": 6.37,
        "financial_health": 3.33,
        "membership_score": 5.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ADRO",
      "name": "Adaro Energy",
      "sector": "Energy (Coal)",
      "price": 2470,
      "change_1d": 0.41,
      "change_ytd": 42.4,
      "change_1y": 47.4,
      "dividend_yield": 9.61,
      "pe_ratio": 8.0,
      "market_cap_t": 71.1,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 3.8,
        "s": 5.5,
        "g": 6.8
      },
      "hybrid_esg_score": 5.04,
      "hybrid_breakdown": {
        "pillar_avg": 5.37,
        "financial_health": 7.87,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "PTBA",
      "name": "Bukit Asam",
      "sector": "Energy (Coal)",
      "price": 2320,
      "change_1d": 0.0,
      "change_ytd": 4.7,
      "change_1y": 1.2,
      "dividend_yield": 4.94,
      "pe_ratio": 8.0,
      "market_cap_t": 26.7,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 3.5,
        "s": 5.8,
        "g": 6.5
      },
      "hybrid_esg_score": 4.5,
      "hybrid_breakdown": {
        "pillar_avg": 5.27,
        "financial_health": 6.23,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ANTM",
      "name": "Aneka Tambang",
      "sector": "Mining (Nickel/Gold)",
      "price": 2870,
      "change_1d": -0.35,
      "change_ytd": -4.1,
      "change_1y": 5.8,
      "dividend_yield": 7.29,
      "pe_ratio": 8.1,
      "market_cap_t": 69.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.8,
        "s": 6.4,
        "g": 6.9
      },
      "hybrid_esg_score": 6.84,
      "hybrid_breakdown": {
        "pillar_avg": 6.37,
        "financial_health": 7.2,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INCO",
      "name": "Vale Indonesia",
      "sector": "Mining (Nickel)",
      "price": 5200,
      "change_1d": -1.42,
      "change_ytd": -0.2,
      "change_1y": 40.3,
      "dividend_yield": 1.48,
      "pe_ratio": 19.6,
      "market_cap_t": 54.8,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 6.5,
        "g": 6.8
      },
      "hybrid_esg_score": 4.44,
      "hybrid_breakdown": {
        "pillar_avg": 6.5,
        "financial_health": 3.98,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "MEDC",
      "name": "Medco Energi",
      "sector": "Energy (Oil & Gas)",
      "price": 1305,
      "change_1d": 1.56,
      "change_ytd": -7.6,
      "change_1y": 13.7,
      "dividend_yield": 5.02,
      "pe_ratio": 11.8,
      "market_cap_t": 32.2,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.2,
        "s": 6.0,
        "g": 6.4
      },
      "hybrid_esg_score": 4.68,
      "hybrid_breakdown": {
        "pillar_avg": 5.87,
        "financial_health": 5.81,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "PGAS",
      "name": "Perusahaan Gas Negara",
      "sector": "Utilities (Gas)",
      "price": 1510,
      "change_1d": 0.67,
      "change_ytd": -15.6,
      "change_1y": -0.4,
      "dividend_yield": 8.37,
      "pe_ratio": 8.3,
      "market_cap_t": 36.6,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.5,
        "s": 6.7,
        "g": 7.2
      },
      "hybrid_esg_score": 6.91,
      "hybrid_breakdown": {
        "pillar_avg": 6.47,
        "financial_health": 7.24,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "JSMR",
      "name": "Jasa Marga",
      "sector": "Infrastructure (Toll)",
      "price": 2770,
      "change_1d": 1.09,
      "change_ytd": -14.9,
      "change_1y": -17.7,
      "dividend_yield": 5.7,
      "pe_ratio": 5.7,
      "market_cap_t": 20.1,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.0
      },
      "hybrid_esg_score": 6.88,
      "hybrid_breakdown": {
        "pillar_avg": 6.77,
        "financial_health": 6.65,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "SMGR",
      "name": "Semen Indonesia",
      "sector": "Materials (Cement)",
      "price": 1480,
      "change_1d": 1.37,
      "change_ytd": -43.5,
      "change_1y": -38.9,
      "dividend_yield": 1.94,
      "pe_ratio": 43.5,
      "market_cap_t": 10.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.8,
        "s": 6.5,
        "g": 6.9
      },
      "hybrid_esg_score": 5.34,
      "hybrid_breakdown": {
        "pillar_avg": 6.4,
        "financial_health": 2.13,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INTP",
      "name": "Indocement Tunggal P.",
      "sector": "Materials (Cement)",
      "price": 4800,
      "change_1d": 2.78,
      "change_ytd": -28.4,
      "change_1y": -4.1,
      "dividend_yield": 10.02,
      "pe_ratio": 7.1,
      "market_cap_t": 16.5,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.0,
        "s": 6.7,
        "g": 7.2
      },
      "hybrid_esg_score": 7.1,
      "hybrid_breakdown": {
        "pillar_avg": 6.63,
        "financial_health": 7.6,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BRPT",
      "name": "Barito Pacific",
      "sector": "Petrochemicals/Renew.",
      "price": 1820,
      "change_1d": -1.36,
      "change_ytd": -42.9,
      "change_1y": -29.1,
      "dividend_yield": 9.0,
      "pe_ratio": 16.7,
      "market_cap_t": 170.6,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.4,
        "s": 5.8,
        "g": 5.9
      },
      "hybrid_esg_score": 4.9,
      "hybrid_breakdown": {
        "pillar_avg": 5.7,
        "financial_health": 6.84,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    }
  ]
};
