/* Auto-generated by fetch_data.py v2 · do not edit manually */
window.STOCKS_DATA = {
  "updated": "2026-08-26",
  "source": "Live yfinance + curated IDX/KEHATI flags + curated ESG pillars (Sustainalytics paywall'd)",
  "is_sample": false,
  "methodology": {
    "data_sources": {
      "price_financials": "yfinance (free)",
      "index_membership": "IDX ESG Methodology + KEHATI SRI announcements (curated)",
      "esg_pillars": "Illustrative scores (real Sustainalytics/MSCI need paid API)"
    },
    "hybrid_esg_score": {
      "formula": "0.5*pillar_avg + 0.3*financial_health + 0.2*membership_score",
      "range": "0-10",
      "components": {
        "pillar_avg": "(E + S + G) / 3 from curated ESG pillars",
        "financial_health": "P/E inverse + dividend yield + market cap (normalized)",
        "membership_score": "10=KEHATI+ESG Leaders, 9=ESG Leaders, 7.5=KEHATI, 5=Syariah, 0=none"
      }
    }
  },
  "benchmark": {
    "jkse": {
      "value": 6405.69,
      "change_1d": -1.48,
      "change_ytd": -26.8,
      "change_1y": -19.0,
      "name": "JCI / IHSG",
      "description": "Jakarta Composite Index"
    },
    "jklq45": {
      "value": 632.55,
      "change_1d": -1.46,
      "change_ytd": -25.8,
      "change_1y": -22.6,
      "name": "LQ45",
      "description": "45 most liquid IDX stocks"
    },
    "jci_value": 6405.69,
    "jci_ytd": -26.8,
    "jci_1y": -19.0,
    "jci_1d": -1.48,
    "note": "Multi-index via yfinance; IHSG cross-checked vs live news"
  },
  "stocks": [
    {
      "ticker": "BBCA",
      "name": "Bank Central Asia",
      "sector": "Banking",
      "price": 6350,
      "change_1d": -0.78,
      "change_ytd": -17.4,
      "change_1y": -19.1,
      "dividend_yield": 5.95,
      "pe_ratio": 13.4,
      "market_cap_t": 780.0,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 7.2,
        "g": 8.5
      },
      "hybrid_esg_score": 7.83,
      "hybrid_breakdown": {
        "pillar_avg": 7.5,
        "financial_health": 6.95,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BMRI",
      "name": "Bank Mandiri",
      "sector": "Banking",
      "price": 4160,
      "change_1d": -0.95,
      "change_ytd": -9.0,
      "change_1y": -5.7,
      "dividend_yield": 11.36,
      "pe_ratio": 6.2,
      "market_cap_t": 386.8,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.9
      },
      "hybrid_esg_score": 8.28,
      "hybrid_breakdown": {
        "pillar_avg": 7.07,
        "financial_health": 9.17,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BBRI",
      "name": "Bank Rakyat Indonesia",
      "sector": "Banking",
      "price": 3130,
      "change_1d": -1.57,
      "change_ytd": -8.4,
      "change_1y": -17.1,
      "dividend_yield": 13.14,
      "pe_ratio": 8.0,
      "market_cap_t": 471.3,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 7.5,
        "g": 7.7
      },
      "hybrid_esg_score": 8.32,
      "hybrid_breakdown": {
        "pillar_avg": 7.13,
        "financial_health": 9.18,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BBNI",
      "name": "Bank Negara Indonesia",
      "sector": "Banking",
      "price": 3680,
      "change_1d": 0.0,
      "change_ytd": -6.1,
      "change_1y": -11.9,
      "dividend_yield": 9.49,
      "pe_ratio": 6.6,
      "market_cap_t": 137.1,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.0,
        "s": 6.5,
        "g": 7.2
      },
      "hybrid_esg_score": 7.26,
      "hybrid_breakdown": {
        "pillar_avg": 6.57,
        "financial_health": 8.24,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BRIS",
      "name": "Bank Syariah Indonesia",
      "sector": "Banking (Syariah)",
      "price": 1780,
      "change_1d": -1.39,
      "change_ytd": -16.1,
      "change_1y": -34.3,
      "dividend_yield": 1.82,
      "pe_ratio": 10.3,
      "market_cap_t": 82.1,
      "kehati": false,
      "esg_leaders": false,
      "syariah": true,
      "esg": {
        "e": 6.4,
        "s": 7.8,
        "g": 7.5
      },
      "hybrid_esg_score": 6.25,
      "hybrid_breakdown": {
        "pillar_avg": 7.23,
        "financial_health": 5.45,
        "membership_score": 5.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "TLKM",
      "name": "Telkom Indonesia",
      "sector": "Telecom",
      "price": 2600,
      "change_1d": -0.76,
      "change_ytd": -19.0,
      "change_1y": -13.7,
      "dividend_yield": 8.52,
      "pe_ratio": 14.6,
      "market_cap_t": 256.3,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 7.5,
        "s": 7.6,
        "g": 8.0
      },
      "hybrid_esg_score": 7.99,
      "hybrid_breakdown": {
        "pillar_avg": 7.7,
        "financial_health": 7.13,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ISAT",
      "name": "Indosat Ooredoo H.",
      "sector": "Telecom",
      "price": 2480,
      "change_1d": -5.7,
      "change_ytd": 10.2,
      "change_1y": 25.1,
      "dividend_yield": 4.22,
      "pe_ratio": 10.7,
      "market_cap_t": 80.0,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 6.9,
        "g": 7.0
      },
      "hybrid_esg_score": 5.26,
      "hybrid_breakdown": {
        "pillar_avg": 6.9,
        "financial_health": 6.05,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "EXCL",
      "name": "XL Axiata",
      "sector": "Telecom",
      "price": 2700,
      "change_1d": 0.0,
      "change_ytd": -28.0,
      "change_1y": -3.4,
      "dividend_yield": 5.89,
      "pe_ratio": null,
      "market_cap_t": 49.1,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.7,
        "g": 6.8
      },
      "hybrid_esg_score": 5.03,
      "hybrid_breakdown": {
        "pillar_avg": 6.67,
        "financial_health": 5.66,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "UNVR",
      "name": "Unilever Indonesia",
      "sector": "Consumer Staples",
      "price": 1765,
      "change_1d": -1.94,
      "change_ytd": -27.7,
      "change_1y": 9.5,
      "dividend_yield": 12.67,
      "pe_ratio": 18.0,
      "market_cap_t": 67.0,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 8.2,
        "s": 7.8,
        "g": 8.4
      },
      "hybrid_esg_score": 8.22,
      "hybrid_breakdown": {
        "pillar_avg": 8.13,
        "financial_health": 7.17,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ICBP",
      "name": "Indofood CBP",
      "sector": "Consumer Staples",
      "price": 7850,
      "change_1d": 1.29,
      "change_ytd": 1.1,
      "change_1y": -12.9,
      "dividend_yield": 3.42,
      "pe_ratio": 12.4,
      "market_cap_t": 91.5,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.9,
        "s": 7.2,
        "g": 7.4
      },
      "hybrid_esg_score": 6.78,
      "hybrid_breakdown": {
        "pillar_avg": 7.17,
        "financial_health": 5.65,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INDF",
      "name": "Indofood Sukses Makmur",
      "sector": "Consumer Staples",
      "price": 7275,
      "change_1d": -1.36,
      "change_ytd": 13.8,
      "change_1y": -2.6,
      "dividend_yield": 3.93,
      "pe_ratio": 6.7,
      "market_cap_t": 63.9,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.1
      },
      "hybrid_esg_score": 6.83,
      "hybrid_breakdown": {
        "pillar_avg": 6.8,
        "financial_health": 6.43,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "AMRT",
      "name": "Sumber Alfaria Trijaya",
      "sector": "Consumer Retail",
      "price": 1380,
      "change_1d": -2.47,
      "change_ytd": -28.3,
      "change_1y": -37.6,
      "dividend_yield": 2.93,
      "pe_ratio": 16.0,
      "market_cap_t": 56.7,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 6.8,
        "g": 7.0
      },
      "hybrid_esg_score": 4.79,
      "hybrid_breakdown": {
        "pillar_avg": 6.67,
        "financial_health": 4.86,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ASII",
      "name": "Astra International",
      "sector": "Industrial / Auto",
      "price": 4780,
      "change_1d": -0.21,
      "change_ytd": -26.2,
      "change_1y": -9.2,
      "dividend_yield": 8.14,
      "pe_ratio": 6.5,
      "market_cap_t": 190.8,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 6.8,
        "s": 7.4,
        "g": 8.1
      },
      "hybrid_esg_score": 8.12,
      "hybrid_breakdown": {
        "pillar_avg": 7.43,
        "financial_health": 8.0,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "KLBF",
      "name": "Kalbe Farma",
      "sector": "Healthcare",
      "price": 805,
      "change_1d": 0.0,
      "change_ytd": -31.3,
      "change_1y": -35.8,
      "dividend_yield": 2.48,
      "pe_ratio": 10.1,
      "market_cap_t": 36.4,
      "kehati": true,
      "esg_leaders": true,
      "syariah": false,
      "esg": {
        "e": 7.1,
        "s": 7.5,
        "g": 7.8
      },
      "hybrid_esg_score": 7.35,
      "hybrid_breakdown": {
        "pillar_avg": 7.47,
        "financial_health": 5.38,
        "membership_score": 10.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "KAEF",
      "name": "Kimia Farma",
      "sector": "Healthcare",
      "price": 434,
      "change_1d": -0.91,
      "change_ytd": -16.5,
      "change_1y": -14.1,
      "dividend_yield": null,
      "pe_ratio": null,
      "market_cap_t": 2.4,
      "kehati": false,
      "esg_leaders": false,
      "syariah": true,
      "esg": {
        "e": 6.4,
        "s": 6.9,
        "g": 5.8
      },
      "hybrid_esg_score": 5.17,
      "hybrid_breakdown": {
        "pillar_avg": 6.37,
        "financial_health": 3.29,
        "membership_score": 5.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ADRO",
      "name": "Adaro Energy",
      "sector": "Energy (Coal)",
      "price": 2610,
      "change_1d": -0.76,
      "change_ytd": 50.5,
      "change_1y": 70.6,
      "dividend_yield": 8.99,
      "pe_ratio": 8.6,
      "market_cap_t": 75.2,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 3.8,
        "s": 5.5,
        "g": 6.8
      },
      "hybrid_esg_score": 4.98,
      "hybrid_breakdown": {
        "pillar_avg": 5.37,
        "financial_health": 7.64,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "PTBA",
      "name": "Bukit Asam",
      "sector": "Energy (Coal)",
      "price": 2420,
      "change_1d": -2.42,
      "change_ytd": 9.2,
      "change_1y": 1.3,
      "dividend_yield": 4.62,
      "pe_ratio": 8.3,
      "market_cap_t": 27.9,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 3.5,
        "s": 5.8,
        "g": 6.5
      },
      "hybrid_esg_score": 4.47,
      "hybrid_breakdown": {
        "pillar_avg": 5.27,
        "financial_health": 6.11,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "ANTM",
      "name": "Aneka Tambang",
      "sector": "Mining (Nickel/Gold)",
      "price": 3160,
      "change_1d": -0.94,
      "change_ytd": 5.6,
      "change_1y": 17.8,
      "dividend_yield": 6.58,
      "pe_ratio": 8.9,
      "market_cap_t": 75.9,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.8,
        "s": 6.4,
        "g": 6.9
      },
      "hybrid_esg_score": 6.76,
      "hybrid_breakdown": {
        "pillar_avg": 6.37,
        "financial_health": 6.92,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INCO",
      "name": "Vale Indonesia",
      "sector": "Mining (Nickel)",
      "price": 5200,
      "change_1d": -1.42,
      "change_ytd": -0.2,
      "change_1y": 46.1,
      "dividend_yield": 1.48,
      "pe_ratio": 19.9,
      "market_cap_t": 54.8,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.2,
        "s": 6.5,
        "g": 6.8
      },
      "hybrid_esg_score": 4.43,
      "hybrid_breakdown": {
        "pillar_avg": 6.5,
        "financial_health": 3.93,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "MEDC",
      "name": "Medco Energi",
      "sector": "Energy (Oil & Gas)",
      "price": 1320,
      "change_1d": -5.71,
      "change_ytd": -6.5,
      "change_1y": 13.1,
      "dividend_yield": 4.61,
      "pe_ratio": 12.2,
      "market_cap_t": 32.6,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.2,
        "s": 6.0,
        "g": 6.4
      },
      "hybrid_esg_score": 4.63,
      "hybrid_breakdown": {
        "pillar_avg": 5.87,
        "financial_health": 5.65,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "PGAS",
      "name": "Perusahaan Gas Negara",
      "sector": "Utilities (Gas)",
      "price": 1520,
      "change_1d": -1.3,
      "change_ytd": -15.0,
      "change_1y": -3.8,
      "dividend_yield": 8.16,
      "pe_ratio": 8.6,
      "market_cap_t": 36.8,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.5,
        "s": 6.7,
        "g": 7.2
      },
      "hybrid_esg_score": 6.88,
      "hybrid_breakdown": {
        "pillar_avg": 6.47,
        "financial_health": 7.16,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "JSMR",
      "name": "Jasa Marga",
      "sector": "Infrastructure (Toll)",
      "price": 2740,
      "change_1d": -0.72,
      "change_ytd": -15.8,
      "change_1y": -15.5,
      "dividend_yield": 5.66,
      "pe_ratio": 5.7,
      "market_cap_t": 19.9,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.5,
        "s": 6.8,
        "g": 7.0
      },
      "hybrid_esg_score": 6.88,
      "hybrid_breakdown": {
        "pillar_avg": 6.77,
        "financial_health": 6.64,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "SMGR",
      "name": "Semen Indonesia",
      "sector": "Materials (Cement)",
      "price": 1490,
      "change_1d": -1.0,
      "change_ytd": -43.1,
      "change_1y": -45.4,
      "dividend_yield": 1.88,
      "pe_ratio": 43.8,
      "market_cap_t": 10.0,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.8,
        "s": 6.5,
        "g": 6.9
      },
      "hybrid_esg_score": 5.33,
      "hybrid_breakdown": {
        "pillar_avg": 6.4,
        "financial_health": 2.11,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "INTP",
      "name": "Indocement Tunggal P.",
      "sector": "Materials (Cement)",
      "price": 5500,
      "change_1d": -3.08,
      "change_ytd": -17.9,
      "change_1y": -14.1,
      "dividend_yield": 8.25,
      "pe_ratio": 7.8,
      "market_cap_t": 18.9,
      "kehati": true,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 6.0,
        "s": 6.7,
        "g": 7.2
      },
      "hybrid_esg_score": 6.93,
      "hybrid_breakdown": {
        "pillar_avg": 6.63,
        "financial_health": 7.06,
        "membership_score": 7.5,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    },
    {
      "ticker": "BRPT",
      "name": "Barito Pacific",
      "sector": "Petrochemicals/Renew.",
      "price": 1750,
      "change_1d": -5.91,
      "change_ytd": -45.1,
      "change_1y": -19.6,
      "dividend_yield": 9.0,
      "pe_ratio": 65.8,
      "market_cap_t": 164.0,
      "kehati": false,
      "esg_leaders": false,
      "syariah": false,
      "esg": {
        "e": 5.4,
        "s": 5.8,
        "g": 5.9
      },
      "hybrid_esg_score": 4.37,
      "hybrid_breakdown": {
        "pillar_avg": 5.7,
        "financial_health": 5.05,
        "membership_score": 0.0,
        "weights": {
          "pillar": 0.5,
          "financial": 0.3,
          "membership": 0.2
        }
      }
    }
  ]
};
